// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeSheet.Infrastructure.Data;

#nullable disable

namespace TimeSheet.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TimesheetDbContext))]
    [Migration("20260826145042_AddExpenseEntryKind")]
    partial class AddExpenseEntryKind
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("TimeSheet.Domain.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseReportingCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultInvoiceMonthEndDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseReportingCurrency = "GBP",
                            DefaultInvoiceMonthEndDay = 31
                        });
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesheetEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetEntryId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Customers");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Account");

                    b.Property<string>("BillingAddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCity")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Currency");

                    b.Property<int?>("InvoicingMonthEndDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Active");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerName");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryContactName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode")
                        .IsUnique();

                    b.HasIndex("CurrencyId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.ClientAccountManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AssignedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClientId", "UserId")
                        .IsUnique();

                    b.ToTable("ClientAccountManagers");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Currency");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("CurrencyCode");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("CurrencyName");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("ExchangeRate");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastUpdated");

                    b.HasKey("Id");

                    b.ToTable("Currency", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.CurrencyExchangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_History");

                    b.Property<DateTimeOffset>("ChangeDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ChangeDate");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Currency");

                    b.Property<decimal>("NewExchangeRate")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("NewExchangeRate");

                    b.Property<decimal>("OldExchangeRate")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("OldExchangeRate");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("CurrencyExchangeHistory", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.CurrencyRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrency", "QuoteCurrency", "RateDate")
                        .IsUnique();

                    b.ToTable("CurrencyRates");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Escalation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BudgetLimitAtTimeOfEntry")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CumulativeValueAtTimeOfEntry")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RaisedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesheetEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Decision");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TimesheetEntryId");

                    b.ToTable("Escalations");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.ExpenseEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "Date");

                    b.ToTable("ExpenseEntries");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinalizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinalizedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PdfContent")
                        .HasColumnType("BLOB");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportingCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "InvoiceNumber")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Finalized'");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Hours")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProjectId");

                    b.ToTable("InvoiceLineItems");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedTimesheetEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Projects");

                    b.Property<int>("BudgetAlertThresholdPercent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BudgetHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("CanInvoice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CanInvoice");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Customers");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyOverride")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FixedFeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Active");

                    b.Property<int?>("LatestHealthAssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ProjectName");

                    b.Property<int>("PaymentModel")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Code")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.ProjectHealthAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiModelUsed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AssessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContributingFactorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PercentBudgetConsumed")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PercentTimeElapsed")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "AssessedAtUtc");

                    b.ToTable("ProjectHealthAssessments");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.RecordedTimeArchive", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_RecordedTimes");

                    b.Property<string>("ApprovedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ApprovedByName");

                    b.Property<int?>("ApprovedByStaffId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApprovedPayroll")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Customers");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedDate");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("TaskDate");

                    b.Property<DateTimeOffset?>("DateApprovedPayroll")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateSentToPayroll")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<decimal?>("ExpensesValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ExpensesValue");

                    b.Property<decimal>("OutOfHoursHours")
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT")
                        .HasColumnName("OutOfHours");

                    b.Property<string>("PostingBatch")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("PostingBatch");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Projects");

                    b.Property<string>("SentByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("SentByName");

                    b.Property<int?>("SentByStaffId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SentToPayroll")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ToCompany")
                        .HasPrecision(7, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ToCompany");

                    b.Property<decimal>("ToPayroll")
                        .HasPrecision(7, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ToPayroll");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Staff");

                    b.Property<decimal>("WorkHours")
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT")
                        .HasColumnName("WorkHours");

                    b.HasKey("Id");

                    b.ToTable("RecordedTimesarc", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.StaffCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_StaffCosts");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Customers");

                    b.Property<decimal>("CustomerRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerRate");

                    b.Property<decimal>("OutOfHoursCost")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("OutOfHoursCost");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Staff");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("StaffId", "ClientId")
                        .IsUnique();

                    b.ToTable("StaffCosts", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.StaffCostHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_History");

                    b.Property<DateTimeOffset>("ChangeDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NewCustomerRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NewOutOfHoursCost")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OldCustomerRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OldOutOfHoursCost")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffCostId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_StaffCosts");

                    b.HasKey("Id");

                    b.HasIndex("StaffCostId");

                    b.ToTable("StaffCostsHistory", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.StaffProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_StaffProjects");

                    b.Property<decimal?>("AllocatedHoursPerWeek")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("AllocatedHoursPerWeek");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Active");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Projects");

                    b.Property<int>("StaffCostId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_StaffCosts");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StaffCostId", "ProjectId")
                        .IsUnique();

                    b.ToTable("StaffProjects", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.TimesheetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_RecordedTimes");

                    b.Property<string>("ApprovedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ApprovedByName");

                    b.Property<int?>("ApprovedByStaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ApprovedByStaffId");

                    b.Property<bool>("ApprovedPayroll")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ApprovedPayroll");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Customers");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedDate");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("TaskDate");

                    b.Property<DateTimeOffset?>("DateApprovedPayroll")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateApprovedPayroll");

                    b.Property<DateTimeOffset?>("DateSentToPayroll")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateSentToPayroll");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<decimal?>("ExpensesValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ExpensesValue");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutOfHoursHours")
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT")
                        .HasColumnName("OutOfHours");

                    b.Property<string>("PostingBatch")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("PostingBatch");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Projects");

                    b.Property<string>("SentByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("SentByName");

                    b.Property<int?>("SentByStaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SentByStaffId");

                    b.Property<bool>("SentToPayroll")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SentToPayroll");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToCompany")
                        .HasPrecision(7, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ToCompany");

                    b.Property<decimal>("ToPayroll")
                        .HasPrecision(7, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ToPayroll");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Staff");

                    b.Property<decimal>("WorkHours")
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT")
                        .HasColumnName("WorkHours");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Date");

                    b.HasIndex("ProjectId", "Date");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("RecordedTimes", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PK_Staff");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("FullName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("EntraObjectId");

                    b.Property<decimal?>("HourlyCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("HourlyCost");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Active");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PayrollNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("PayrollNumber");

                    b.Property<bool>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Admin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.TimesheetEntry", "TimesheetEntry")
                        .WithMany("Attachments")
                        .HasForeignKey("TimesheetEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimesheetEntry");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Client", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.ClientAccountManager", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Client", "Client")
                        .WithMany("AccountManagers")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeSheet.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.CurrencyExchangeHistory", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Escalation", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeSheet.Domain.Entities.TimesheetEntry", "TimesheetEntry")
                        .WithMany()
                        .HasForeignKey("TimesheetEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("TimesheetEntry");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.ExpenseEntry", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeSheet.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeSheet.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Project", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.ProjectHealthAssessment", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.StaffCost", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeSheet.Domain.Entities.User", "Staff")
                        .WithMany("StaffCosts")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.StaffCostHistory", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.StaffCost", "StaffCost")
                        .WithMany()
                        .HasForeignKey("StaffCostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffCost");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.StaffProject", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeSheet.Domain.Entities.StaffCost", "StaffCost")
                        .WithMany("StaffProjects")
                        .HasForeignKey("StaffCostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("StaffCost");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.TimesheetEntry", b =>
                {
                    b.HasOne("TimeSheet.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeSheet.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeSheet.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Client", b =>
                {
                    b.Navigation("AccountManagers");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.Project", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.StaffCost", b =>
                {
                    b.Navigation("StaffProjects");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.TimesheetEntry", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("TimeSheet.Domain.Entities.User", b =>
                {
                    b.Navigation("StaffCosts");
                });
#pragma warning restore 612, 618
        }
    }
}
